export const images = {
    'Mattar Paneer': '/matterPanner.jpeg',
    'Saag Paneer': '/saagPanner.jpeg',
    'Chilli Paneer': '/p.jpg',
    'Paneer Tikka': '/paneerTikka.jpeg',
    'Vegetable Biryani': '/vb.jpg',
    'Paneer Biryani': '/paneerBiryani.jpg',
    'Mushroom Biryani': '/mb.jpg',
    'Jeera Rice': '/jr.jpg',
    'Veg Fried Rice': '/vegFriedRIce.webp',
    'Andhra Pulao': '/ap.jpg',
    'Vegetable Spring Rolls': '/vsgs.jpg', 
    'Stuffed Mushrooms': '/mushroomRecipe.jpeg',
    'Hara Bhara Kabab': '/haraBaraKabab.jpg',
    'Paneer Butter Masala': '/pbm.jpg',
    'Aloo Gobi': '/alooGobi.jpg',
    'Chana Masala': '/chanaMasala.jpg',
    'Gobi Manchurian': '/vm.jpg',
    'Baby Corn Chilly': '/babyCornChilli.jpeg',
    'Palak Paneer':'/palak.jpeg',
    'Paneer 65':'/p5.jpg',
    'Mixed Veg Curry': '/vegMixCurry.jpg',
    'Methi Chaman': '/methiChaman.jpeg',
    'Chicken Wings Biryani':'/cwb.jpeg',
    'Mutton Dum biriyani':'/mbs.jpg',
    'Mutton Curry':'/nonveg/mc.jpg',
    'Mutton Haleem':'/nonveg/mh.jpg',
    'Mutton Ghee Roast':'/nonveg/msd.jpg',
    'Mutton Manchurian':'/nonveg/mman.jpg',
    'Punjabi Mutton Curry':'/nonveg/pmc.jpg',
    'Mughlai Karahi Gosht':'/nonveg/mmc.jpg',
    'Pepper Mutton':'/nonveg/pm.jpg',
    'Mutton Chaap':'/nonveg/mcha.jpg',
    'Kashmiri Rogan Josh':'/nonveg/krj.jpg',
    'Shahi Mutton Curry':'/nonveg/smc.jpg',
    'Chicken Shangrilla':'/nonveg/csh.jpg',
    'Kadai Chicken':'/nonveg/kc.jpg',
    'Dragon Chicken':'/nonveg/dc.jpg',
    'Andhra Chicken Curry (Boneless)':'/nonveg/acc.jpg',
    'Chicken Tikka':'/nonveg/cts.jpg',
    'Chicken Wings':'/nonveg/cws.jpg',
    'Butter Chicken (Murgh Makhani)':'/nonveg/bc.jpg',
    'Fish Curry':'/nonveg/fc.jpg',
    'Fish Tacos':'/nonveg/ft.jpg',
    'Garlic Butter Prawns':'/nonveg/gbp.jpg',
    'Crab Curry':'/nonveg/cc.jpg',
    'Crab Fry':'/nonveg/cfs.jpg',
    'Prawns Butter Masala':'/nonveg/pbms.jpg',
    'Prawns 65':'/nonveg/p65.jpg',
    'Rajugari Chepala Pulusu':'/nonveg/rcps.jpg',
    'Fish Fry':'/nonveg/ffs.jpg',
    'Chicken Wings Biryani':'/nonveg/cwbir.jpg',
    'Gongura Chicken Biryani':'/nonveg/gcbs.jpg',
    'Mutton Fry Piece Biryani':'/nonveg/mfp2.jpg',
    'Prawn Biryani':'/nonveg/pbs.jpg',
    'Mutton Biryani':'/nonveg/mbir.jpg',
    'Dhumm Chicken Biryani':'/nonveg/dcbs.jpg',
    'Mutton Dum biryani':'/nonveg/dmb.jpg',  
  };